### ISSUE TITLE
User can edit an entry

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/code-journal#14]
## Task List

- [ ] Create an html `anchor` element for each entry created to represent the edit button.
- [ ] Listen for clicks on the edit button.
- [ ] When the edit button is clicked, the edit-entry view appears with the previous information filled in.
- [ ] The data object model gets updated with the edited information.
